name: kenburns
description: Kenburns effect on flutter. The Ken Burns effect is a type of panning and zooming effect used in video production from still imagery.
version: 1.0.5
#author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/florent37/Flutter-KenBurns

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
